import PrelineScript from "@/components/PrelineScript";
import { availableLocalesMap, defaultLocale } from "@/next.locales.mjs";
import { LocaleProvider } from "@/providers/localeProvider";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import { notFound } from "next/navigation";
import "./globals.css";
interface RootLayoutProps {
	children: React.ReactNode;
	params: {
		locale: string;
	};
}

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const locales = ["en", "ar"];

export default function RootLayout({
	children,
	params: { locale },
}: RootLayoutProps) {
	// biome-ignore lint/suspicious/noExplicitAny: I didn't find a way to fix it
	if (!locales.includes(locale as any)) notFound();

	const { langDir, hrefLang } = availableLocalesMap[locale] || defaultLocale;

	return (
		<html lang={hrefLang} dir={langDir}>
			<body>
				<LocaleProvider>
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</LocaleProvider>
			</body>
			<PrelineScript />
		</html>
	);
}
