import PrelineScript from "@/components/site/preline-script";
import { availableLocalesMap, defaultLocale } from "@/next.locales.mjs";
import { LocaleProvider } from "@/providers/locale-provider";
import ReactQueryProvider from "@/providers/react-query-provider";
import { notFound } from "next/navigation";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@ikseer/ui/src/components/ui/toaster";
import type React from "react";
import GuestNavBar from "./_components/nav-bar";

interface RootLayoutProps {
	children: React.ReactNode;
	params: {
		locale: string;
	};
}

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const locales = ["en", "ar"];

export default function RootLayout({
	children,
	params: { locale },
}: RootLayoutProps) {
	// biome-ignore lint/suspicious/noExplicitAny: I didn't find a way to fix it
	if (!locales.includes(locale as any)) notFound();

	const { langDir, hrefLang } = availableLocalesMap[locale] || defaultLocale;

	return (
		<html lang={hrefLang} dir={langDir}>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<LocaleProvider>
						<ReactQueryProvider>
							<GuestNavBar />

							{children}
						</ReactQueryProvider>
						<Toaster />
					</LocaleProvider>
				</ThemeProvider>
			</body>
			<PrelineScript />
		</html>
	);
}
