import "./globals.css";
import Providers from "./provider";
import ThemeSwitcher from "./switchMode";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" >
      <body>
        <Providers>
          <ThemeSwitcher />
            {children}
        </Providers>
      </body>
    </html>
  );
}