export const EgyptGovernorate = {
	en: [
		"Cairo",
		"Giza",
		"Alexandria",
		"Al Beheira",
		"Al Daqahliya",
		"Al Fayoum",
		"Al Gharbia",
		"Al Meniya",
		"Al Monufia",
		"Al Sharqia",
		"Aswan",
		"Asyut",
		"Bani Souaif",
		"Damietta",
		"Ismailia",
		"Kafr El Sheikh",
		"Luxor",
		"Matrooh",
		"New Valley",
		"Port Said",
		"Qalyubia",
		"Qena",
		"Red Sea",
		"Sohag",
		"Suez",
		"North Sinai",
		"South Sinai",
	],
	ar: [
		"القاهرة",
		"الجيزة",
		"الاسكندرية",
		"البحيرة",
		"الدقهلية",
		"الفيوم",
		"الغربية",
		"المنيا",
		"المنوفية",
		"الشرقية",
		"أسوان",
		"أسيوط",
		"بني سويف",
		"دمياط",
		"الاسماعيلية",
		"كفر الشيخ",
		"الأقصر",
		"مطروح",
		"الوادي الجديد",
		"بورسعيد",
		"القليوبية",
		"قنا",
		"البحر الاحمر",
		"سوهاج",
		"السويس",
		"شمال سيناء",
		"جنوب سيناء",
	],
} as const;

export const EgyptCities = {
	Cairo: {
		ar: [
			"حدائق الزيتون",
			"الشروق",
			"المعادي دجلة",
			"العباسية",
			"النزهة الجديدة",
			"دار السلام",
			"القلعة",
			"البساتين",
			"عبده باشا",
			"مدينة ناصر",
			"مدينة 15 مايو",
			"التجمع الخامس",
			"مصر الجديدة",
			"التجمع الثالث",
			"عزبة النخل",
			"قطامية",
			"الحرفيين",
			"وسط البلد",
			"المرج",
			"المعادى الجديدة",
			"الزمالك",
			"التجمع الاول",
			"حلوان",
			"الزيتون",
			"مساكن شيراتون",
			"حدائق حلوان",
			"غمره",
			"روض الفرج",
			"المطرية",
			"القصر العيني",
			"القاهرة",
			"القاهرة الجديدة",
			"عين شمس",
			"جاردن سيتي",
			"ميراج سيتى",
			"العامرية",
			"الأزهر",
			"السيدة زينب",
			"الماظة",
			"الفسطاط",
			"حدائق المعادي",
			"الرحاب",
			"الموسكي",
			"منيل الروضة",
			"المعادى",
			"التحرير",
			"نيو المرج",
			"جسر السويس",
			"عابدين",
			"المقطم",
			"مدينة السلام",
			"مصر القديمة",
			"حلمية الزيتون",
			"الضاهر",
			"حدائق القبة",
			"شبرا",
			"كورنيش النيل",
			"مدينة بدر",
			"رمسيس",
			"مدينتي",
			"الحلمية",
		],
		en: [
			"Hadayek Al Zaiton",
			"El Shorouk",
			"El Marg",
			"Maadi Degla",
			"Abaseya",
			"New Nozha",
			"Dar Al Salam",
			"Al Kalaa",
			"Basateen",
			"Abdo Basha",
			"Nasr City",
			"15th Of May City",
			"5th Settlement",
			"Heliopolis",
			"3rd Settlement",
			"Ezbet El Nakhl",
			"Katamiah",
			"El Herafiee",
			"15th of May Cit",
			"Down Tow",
			"EL Mar",
			"New Maad",
			"Zamale",
			"1st Settlemen",
			"Helwa",
			"Al Zeitou",
			"Masaken Sherato",
			"Hadayek Helwa",
			"Ghamra",
			"Rod El Fara",
			"Al Matarey",
			"Al Kasr Al Ein",
			"Cair",
			"New Cair",
			"Ain Sham",
			"Garden Cit",
			"Mirage Cit",
			"Amiri",
			"Al Azha",
			"Sayeda Zeina",
			"Almaz",
			"Fusta",
			"Hadayek Maad",
			"Al Reha",
			"Al Mosk",
			"Manial Al Roda",
			"Maad",
			"El Tahri",
			"New El Mar",
			"Gesr Al Sue",
			"Abdee",
			"Mokatta",
			"Al Salam Cit",
			"Misr El Kadim",
			"Helmiet Elzaitou",
			"Al Dahe",
			"Hadayek Al Qoba",
			"Shubr",
			"Cornish Al Nil",
			"Badr Cit",
			"Ramsi",
			"Madint",
			"Helmey",
		],
	},
	Giza: {
		en: [
			"6th of October",
			"Mansoureya",
			"Hawamdya",
			"Tirsa",
			"Abou Rawash",
			"Omraneya",
			"Smart Village",
			"Kerdasa",
			"Saft El Laban",
			"Dokki",
			"Al Saf",
			"Sheikh Zayed",
			"Sakiat Mekki",
			"Mohandessin",
			"Al Kom Al Ahmer",
			"Imbaba",
			"Bolak Al Dakrour",
			"Al Monib",
			"Berak Alkiaam",
			"Al Moatamadia",
			"Shabramant",
			"Warraq",
			"Giza",
			"Manial",
			"Haram",
			"Agouza",
			"Qism el Giza",
			"Faisal",
			"Al Wahat",
			"Hadayeq El Ahram",
			"6th Of October",
			"Aossim",
			"Al Nobariah",
			"Badrashin",
			"Kit Kat",
			"Al Barageel",
			"Al Manashi",
		],
		ar: [
			"السادس من اكتوبر",
			"المنصورية",
			"الحوامدية",
			"تيرسا",
			"ابو رواش",
			"العمرانية",
			"القرية الذكية",
			"كرداسة",
			"صفط اللبن",
			"الدقي",
			"الصف",
			"الشيخ زايد",
			"ساقية مكي",
			"المهندسين",
			"الكوم الأحمر",
			"إمبابة",
			"بولاق الدكرور",
			"المنيب",
			"برك الكيام",
			"المعتمدية",
			"شبرامانت",
			"الوراق",
			"الجيزة",
			"المنيل",
			"الهرم",
			"العجوزة",
			"قسم الجيزة",
			"فيصل",
			"الواحات",
			"حدائق الاهرام",
			"أوسيم",
			"النوبارية",
			"بدراشين",
			"كت كات",
			"البراجيل",
			"المناشي",
		],
	},
	Alexandria: {
		en: [
			"Miami",
			"Smouha",
			"Abees",
			"Alexandria",
			"Sedi Gaber",
			"El Borg El Kadem",
			"Sedi Bisher",
			"Al Bitash",
			"Stanly",
			"El-Agamy",
			"San Stefano",
			"Mahtet El-Raml",
			"Al A'mriah",
			"Bangar EL Sokar",
			"Manshia",
			"Sedi Kreir",
			"Kafer Abdou",
			"Borg El Arab",
			"Roshdy",
			"Abu Keer",
			"Glem",
			"Al Nahda Al Amria",
			"Awaied-Ras Souda",
			"Mandara",
			"City Center",
			"Azarita",
			"Maamora",
			"Al Soyof",
			"Sporting",
			"Khorshid",
			"Luran",
			"Asafra",
			"Zezenya",
			"Muntazah",
		],
		ar: [
			"ميامي",
			"سموحة",
			"أبيس",
			"الإسكندرية",
			"سيدي جابر",
			"البرج القديم",
			"سيدي بشر",
			"البيطاش",
			"ستانلي",
			"العجمي",
			"سان ستيفانو",
			"محطة الرمل",
			"العامرية",
			"بنجر السكر",
			"المنشية",
			"سيدي كرير",
			"كفر عبده",
			"برج العرب",
			"رشدي",
			"ابو قير",
			"جليم",
			"النهضة العامرية",
			"عويد راس سودا",
			"المندرة",
			"وسط المدينة",
			"أزاريتا",
			"المعمورة",
			"السيوف",
			"سبورتنج",
			"خورشيد",
			"لوران",
			"العصافرة",
			"زيزينيا",
			"المنتزه",
		],
	},
	"Al Beheira": {
		en: [
			"Hosh Issa",
			"Rashid",
			"Shubrakhit",
			"Edko",
			"Damanhour",
			"Etay Al Barud",
			"Al Beheira",
			"Abu Hummus",
			"Kom Hamadah",
			"Abou Al Matamer",
			"Al Delengat",
			"El Nubariyah",
			"Kafr El Dawwar",
			"Edfina",
			"Wadi Al Natroun",
			"Al Mahmoudiyah",
			"Al Rahmaniyah",
		],
		ar: [
			"حوش عيسى",
			"رشيد",
			"شبراخيت",
			"إدكو",
			"دمنهور",
			"ايتاي البارود",
			"البحيرة",
			"ابو حمص",
			"كوم حمادة",
			"ابو المطامير",
			"الدلنجات",
			"النوبارية",
			"كفر الدوار",
			"إدفينا",
			"وادي النطرون",
			"المحمودية",
			"الرحمانية",
		],
	},
	"Al Daqahliya": {
		en: [
			"Meet Ghamr",
			"Belqas",
			"Nabroo",
			"Manzala",
			"Shrbeen",
			"Al Daqahliya",
			"El Sinblaween",
			"Menit El Nasr",
			"Dekernes",
			"Aga",
			"Talkha",
			"Al Mansoura",
		],
		ar: [
			"ميت غمر",
			"بلقاس",
			"نابرو",
			"المنزلة",
			"شربين",
			"الدقهلية",
			"السنبلاوين",
			"منية النصر",
			"دكرنس",
			"آغا",
			"طلخا",
			"المنصورة",
		],
	},
	"Al Fayoum": {
		en: [
			"Sonores",
			"Ebshoy",
			"Kofooer Elniel",
			"New Fayoum",
			"Atsa",
			"Sanhoor",
			"Tameaa",
			"Al Fayoum",
			"Sersenaa",
			"El Aagamen",
			"Manshaa Abdalla",
			"Youssef Sadek",
			"Manshaa Elgamal",
		],
		ar: [
			"سنورس",
			"إبشواي",
			"كفور النيل",
			"الفيوم الجديدة",
			"اطسا",
			"سنهور",
			"طامية",
			"الفيوم",
			"سيرسينا",
			"العجمين",
			"منشاء عبد الله",
			"يوسف صادق",
			"منشأة الجمال",
		],
	},
	"Al Gharbia": {
		en: [
			"Alsanta",
			"Al Mahala Al Kobra",
			"Al Gharbia",
			"Samanood",
			"Tanta",
			"Qotoor",
			"Zefta",
			"Basyoon",
			"Kafr Alziat",
		],
		ar: [
			"السنطة",
			"المحلة الكبرى",
			"الغربية",
			"سمنود",
			"طنطا",
			"قطور",
			"زفتى",
			"بسيون",
			"كفر الزيات",
		],
	},

	"Al Meniya": {
		ar: [
			"المنيا",
			"سمالوط",
			"العدوة",
			"مغاغة",
			"مطاى",
			"ملاوي",
			"بني مزار",
			"ديرماس",
			"ابو قرقاص",
		],
		en: [
			"Minya",
			"Samaloot",
			"Eladwa",
			"Mghagha",
			"Matai",
			"Malawi",
			"Bani Mazar",
			"Dermwas",
			"Abo Korkas",
		],
	},

	"Al Monufia": {
		en: [
			"Shohada",
			"Menoof",
			"Tala",
			"Shebin El Koom",
			"Sadat City",
			"Al Monufia",
			"Quesna",
			"Berket Al Sabei",
			"Ashmoon",
		],
		ar: [
			"الشهداء",
			"منوف",
			"تلا",
			"شبين الكوم",
			"مدينة السادات",
			"المنوفية",
			"قويسنا",
			"بركة السبع",
			"أشمون",
		],
	},

	"Al Sharqia": {
		en: [
			"Faqous",
			"Zakazik",
			"Al Salhiya Al Gedida",
			"Abu Hammad",
			"Abu Kbeer",
			"Hehya",
			"Awlad Saqr",
			"Al Hasiniya",
			"Darb Negm",
			"Al Ibrahimiya",
			"Kafr Saqr",
			"Mashtool Al Sooq",
			"Belbes",
			"Meniya Alqamh",
			"Al Sharqia",
			"10th of Ramdan City",
		],
		ar: [
			"الزقازيق",
			"فاقوس",
			"الصالحية الجديدة",
			"ابو حماد",
			"ابو كبير",
			"ههيا",
			"اولاد صقر",
			"الحسينية",
			"درب نجم",
			"الابراهيمية",
			"كفر صقر",
			"مشتول السوق",
			"بيلبيس",
			"منيا القمه",
			"الشرقية",
			"العاشر من رمضان",
		],
	},

	Aswan: {
		en: [
			"Aswan",
			"Draw",
			"El Klabsha",
			"Al Sad Al Aali",
			"Abu Simbel",
			"Nasr Elnoba",
			"Edfo",
			"Markaz Naser",
			"Kom Ombo",
		],
		ar: [
			"أسوان",
			"دراو",
			"كلابشة",
			"السد العالي",
			"أبو سمبل",
			"نصر النوبة",
			"إدفو",
			"مركز ناصر",
			"كوم امبو",
		],
	},
	Asyut: {
		en: [
			"Dayrout",
			"Asyut",
			"El Qusya",
			"Assuit Elgdeda",
			"Elfath",
			"El Ghnayem",
			"Sahel Selim",
			"Abnoub",
			"El Badari",
			"Abou Teag",
			"Serfa",
			"Manflout",
		],
		ar: [
			"ديروط",
			"أسيوط",
			"القوصية",
			"اسيوط الجديدة",
			"الفتح",
			"الغنايم",
			"ساحل سليم",
			"أبنوب",
			"البدارى",
			"ابو تيج",
			"سيرفا",
			"منفلوط",
		],
	},
	"Bani Souaif": {
		en: [
			"Bani Souaif",
			"El Wastaa",
			"El Korimat",
			"El Fashn",
			"Naser",
			"Ahnaseaa",
			"New Bani Souaif",
			"Bebaa",
			"Smostaa",
		],
		ar: [
			"بني سويف",
			"الواسطى",
			"الكريمات",
			"الفشن",
			"ناصر",
			"إهناسيا",
			"بني سويف الجديدة",
			"ببا",
			"سمسطا",
		],
	},

	Damietta: {
		ar: ["كفر سعد", "رأس البر", "فارسكور", "الزرقا", "دمياط", "دمياط الجديدة"],
		en: [
			"Kafr Saad",
			"Ras El Bar",
			"Fareskor",
			"Al Zarkah",
			"Damietta",
			"New Damietta",
		],
	},

	Ismailia: {
		en: [
			"Elsalhia Elgdida",
			"Al Kasaseen",
			"Abo Sultan",
			"El Tal El Kebir",
			"Abu Swer",
			"Qantara Gharb",
			"Qantara Sharq",
			"Nfeesha",
			"Ismailia",
			"Srabioom",
			"Fayed",
		],
		ar: [
			"الصالحية الجديدة",
			"القصاصين",
			"ابو سلطان",
			"التل الكبير",
			"ابو صوير",
			"قنطرة غرب",
			"القنطرة شرق",
			"نفيشة",
			"الإسماعيلية",
			"سرابيوم",
			"فايد",
		],
	},

	"Kafr El Sheikh": {
		en: [
			"Hamool",
			"Kafr El Sheikh",
			"Al Riadh",
			"Qeleen",
			"Desouq",
			"Seedy Salem",
			"Bela",
			"Fooh",
			"Metobas",
			"Borollos",
			"Balteem",
		],
		ar: [
			"الحامول",
			"كفر الشيخ",
			"الرياض",
			"قلين",
			"دسوق",
			"سيدى سالم",
			"بيلا",
			"فوه",
			"مطوبس",
			"برج البرلس",
			"بلطيم",
		],
	},

	Luxor: {
		en: [
			"El Karnak",
			"El Korna",
			"Armant Sharq",
			"Esnaa",
			"Luxor",
			"Armant Gharb",
		],
		ar: ["الكرنك", "القرنة", "ارمنت شرق", "اسنا", "الأقصر", "ارمنت غرب"],
	},

	Matrooh: {
		en: [
			"Matrooh",
			"El Alamein",
			"Sidi Abdel Rahman",
			"El Dabaa",
			"Marsa Matrooh",
		],
		ar: ["مطروح", "العلمين", "سيدي عبد الرحمن", "الضبعة", "مرسى مطروح"],
	},

	"New Valley": {
		en: ["El Kharga", "New Valley"],
		ar: ["الخارجة", "الوادي الجديد"],
	},

	"Port Said": {
		en: ["Port Fouad", "Port Said", "Zohoor District"],
		ar: ["بور فؤاد", "بورسعيد", "حي الزهور"],
	},
	Qalyubia: {
		en: [
			"Abu Zaabal",
			"Qaha",
			"Tookh",
			"El Oboor",
			"Meet Nama",
			"Al Shareaa Al Gadid",
			"Banha",
			"El Kanater EL Khayrya",
			"Sheben Alkanater",
			"El Qalag",
			"Bahteem",
			"Qalyubia",
			"Orabi",
			"Qalyoob",
			"Al Khanka",
			"El Khsos",
			"Kafr Shokr",
			"Om Bayoumi",
			"Shoubra Alkhema",
			"Mostorod",
		],
		ar: [
			"ابو زعبل",
			"قها",
			"طوخ",
			"العبور",
			"ميت نما",
			"الشريعة الجديد",
			"بنها",
			"القناطر الخيرية",
			"شبين القناطر",
			"القلج",
			"بهتيم",
			"القليوبية",
			"عرابي",
			"قليوب",
			"الخانكة",
			"الخصوص",
			"كفر شكر",
			"أم بيومي",
			"شبرا الخيمة",
			"مسطرد",
		],
	},
	Qena: {
		en: [
			"Deshna",
			"Abu Tesht",
			"Farshoot",
			"Qena",
			"Qoos",
			"Naqada",
			"Naga Hamadi",
		],
		ar: ["دشنا", "ابوتشت", "فرشوط", "قنا", "قوص", "نقادة", "نجع حمادي"],
	},
	"Red Sea": {
		en: [
			"Red Sea",
			"Safaga",
			"Hurghada",
			"Qouseir",
			"Marsa Alam",
			"Gouna",
			"Ras Ghareb",
		],
		ar: [
			"البحر الاحمر",
			"سفاجا",
			"الغردقة",
			"القصير",
			"مرسى علم",
			"الجونة",
			"رأس غارب",
		],
	},
	Sohag: {
		en: [
			"Sohag",
			"Tema",
			"Saqatlah",
			"Dar Elsalam",
			"Gerga",
			"Elbalyna",
			"Maragha",
			"El Monshah",
			"Ghena",
			"Akhmem",
			"Tahta",
		],
		ar: [
			"سوهاج",
			"طما",
			"ساقلته",
			"دار السلام",
			"جرجا",
			"البالينا",
			"مراغة",
			"المنشاه",
			"جهينة",
			"أخميم",
			"طهطا",
		],
	},
	Suez: {
		en: [
			"Ataka District",
			"Suez",
			"Elganaien District",
			"Al Suez",
			"Al Adabya",
			"Ain Al Sukhna",
			"El Arbeen District",
		],
		ar: [
			"حي عتاقة",
			"حي الجناين",
			"السويس",
			"الأدبية",
			"العين السخنة",
			"حى الاربعين",
		],
	},
	"North Sinai": {
		en: ["North Sinai", "Al Arish"],
		ar: ["شمال سيناء", "العريش"],
	},
	"South Sinai": {
		en: [
			"Neweibaa",
			"Dahab",
			"Saint Catherine",
			"Sharm Al Sheikh",
			"Toor Sinai",
			"Taba",
		],
		ar: ["نويبع", "دهب", "سانت كاترين", "شرم الشيخ", "طور سيناء", "طابا"],
	},
} satisfies Record<EgyptGovernorateKey, Record<"ar" | "en", string[]>>;

export type EgyptGovernorateKey = (typeof EgyptGovernorate)["en"][number];
