import "./globals.css";
import Providers from "./provider";
import ThemeSwitcher from "./switchMode";
import {notFound} from 'next/navigation';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps  {
  children: React.ReactNode,
  params: {
    locale: string
  }
};

const locales = ['en', 'ar'];

export default function RootLayout({ children, params: {locale} }: RootLayoutProps) {
  if (!locales.includes(locale as any)) notFound();
  return (
    <html lang={locale}>
      <body>
        <Providers>
          <ThemeSwitcher />
            {children}
        </Providers>
      </body>
    </html>
  );
}