// Main
import React from 'react';
import ReactQueryProvider from '@/utils/reactQueryProvider';
import { notFound } from 'next/navigation';


// Dark Theme
import Providers from '@/components/darkTheme/Provider';


// Components
import GuestNavBar from '@/components/Navbar/Navbar';
import PrelineScript from './components/PrelineScript';


// CSS
import './globals.css';


// Interface
interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


const locales = ['en', 'ar'];

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  if (!locales.includes(locale as any)) notFound();

  const dir = locale === 'ar' ? 'rtl' : 'ltr';

  return (
    <html lang={locale} dir={dir}>
      <body>
        <Providers>
          <GuestNavBar />
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </Providers>
      </body>
      <PrelineScript />
    </html>
  );
}
